#!/usr/bin/bash

# Lookup undefined symbols in an object file using `nm`
# usage: ldsearch /path/to/objectfile
# TODO improve display versus 
#    nm -C -u file

OBJECT=$1

if ! [ -f "$OBJECT" ]; then
  printf "enter an object file to search\n"
  exit 1
fi

# search for all Undefined 
nm -C $OBJECT | grep vtable | awk 'BEGIN {FS=" "} { if ($1 ~ /U/) print } '




